cabal-version: 2.4
name:          parallel-and-concurrent
version:       0.1.0.0
build-type:    Simple

executable strategy
  main-is:          Strategy.hs
  build-depends:    base >=4.14 && <5
                  , parallel >=3.2 && <3.4
                  , deepseq >=1.4 && <1.6
  default-language: Haskell2010
  ghc-options:      -threaded

executable nfdata
  main-is:          NFData.hs
  build-depends:    base >=4.14 && <5
  default-language: Haskell2010
  ghc-options:      -threaded

executable eval 
  main-is:          eval.hs
  build-depends:    base >=4.14 && <5
                  , parallel >=3.2 && <3.4
  default-language: Haskell2010
  ghc-options:      -threaded

executable par
  main-is:          Par.hs
  build-depends:    base >=4.14 && <5
					   , monad-par >= 0.3 && <0.4
  default-language: Haskell2010
  ghc-options:      -threaded

executable stream
  main-is:          Stream.hs
  build-depends:    base >=4.14 && <5
  default-language: Haskell2010
  ghc-options:      -threaded

executable repa 
  main-is:          Stream.hs
  build-depends:    base >=4.14 && <5
                  , repa
  default-language: Haskell2010
  ghc-options:      -threaded

executable scratch
  main-is:          Scratch.hs
  build-depends:    base >=4.14 && <5
  default-language: Haskell2010
  ghc-options:      -threaded

executable thread 
  main-is:          ThreadsAndMvars.hs
  build-depends:    base >=4.14 && <5
  default-language: Haskell2010
  ghc-options:      -threaded
  
executable accelerate 
  main-is:          Accelerate.hs
  build-depends:    base >=4.14 && <5
					   , accelerate
  default-language: Haskell2010
  ghc-options:      -threaded

executable async 
  main-is:          Async.hs
  build-depends:    base >=4.14 && <5
  default-language: Haskell2010
  ghc-options:      -threaded


executable exceptions 
  main-is:          Exceptions.hs
  build-depends:    base >=4.14 && <5
  default-language: Haskell2010
  ghc-options:      -threaded

executable stm 
  main-is:          STM.hs
  build-depends:    base >=4.14 && <5
					   , stm
						, containers
  default-language: Haskell2010
  ghc-options:      -threaded

executable server1 
  main-is:          server/SimpleMultiThreaded.hs
  build-depends:    base >=4.14 && <5
                  , network
  default-language: Haskell2010
  ghc-options:      -threaded

executable server2
  main-is:          server/STMServer.hs
  build-depends:    base >=4.14 && <5
                  , network
						, stm
						, async
  default-language: Haskell2010
  ghc-options:      -threaded
